; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = LVGL-320-480
default_envs = esp32-c6-devkitc-1
boards_dir = boards
data_dir = littlefs
lib_dir = libraries
src_dir = src

[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitm-1
framework = arduino
lib_deps = 
	moononournation/GFX Library for Arduino @ ^1.5.9
	adafruit/Adafruit GFX Library @ ^1.11.9
	knolleary/PubSubClient @ ^2.8
	lvgl/lvgl @ ^8.3.11
	links2004/WebSockets @ ^2.3.7
	lovyan03/LovyanGFX@^1.2.7
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 4MB
board_build.partitions = partitions/ota_zigbee_4MB.csv
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D LV_CONF_INCLUDE_SIMPLE
	-I src
	-D BOARD_ESP32C6_TOUCH_1_47
	-D HAS_ZIGBEE=1
	-D ZIGBEE_MODE_ZCZR
	-L $HOME/.platformio/packages/framework-arduinoespressif32-libs/esp32c6/lib
	-lesp_zb_api.zczr
	-lzboss_stack.zczr
	-D FORCE_ZIGBEE=1
	-D CORE_DEBUG_LEVEL=3
extra_scripts = 
	pre:scripts/clean_ds_store.py

[env:esp32-s3-35]
platform = espressif32
#board = esp32-s3-devkitc-1
board = 320x480
framework = arduino
lib_deps = 
	knolleary/PubSubClient @ ^2.8
	links2004/WebSockets @ ^2.3.7
	lvgl/lvgl @ ^8.3.11
	jc3248w535
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-I src
	-I libraries
	-D LV_CONF_INCLUDE_SIMPLE
	-D USE_JC3248W535
	-D BOARD_ESP32S3_35
	-D HAS_ZIGBEE=0
	-D CORE_DEBUG_LEVEL=3
