[platformio]
default_envs = esp32-p4-wrapper-test

[env:esp32-p4-wrapper-test]
platform = espressif32
board = esp32-p4-evboard
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_16MB.csv

lib_deps = 
    lvgl/lvgl @ ^8.4.0

lib_extra_dirs = 
    libraries

build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D LV_CONF_INCLUDE_SIMPLE
	-D LCD_H_RES=480
	-D LCD_V_RES=800
	-D BOARD_ESP32P4_43
	-D CORE_DEBUG_LEVEL=3
	-I .
	-I src
	-I libraries/ESP32P4_Display
	-I libraries/st7701_lcd
	-I libraries/gt911_touch

; no lib_ignore: rely on root libs
