[platformio]
default_envs = esp32-p4-43

[env:esp32-p4-43]
platform = espressif32
board = esp32-p4-evboard
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_16MB.csv

; Library dependencies
lib_deps = 
	lvgl/lvgl @ ^8.4.0
	ESP32P4_Display
	GT911 Touch Driver
	ST7701 LCD Driver

; Build flags
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D LV_CONF_INCLUDE_SIMPLE
	-I ../../src
	-D LCD_H_RES=480
	-D LCD_V_RES=800
	-D BOARD_ESP32P4_43
	-D CORE_DEBUG_LEVEL=3